### ISSUE TITLE
MySql client error when use some command

### ISSUE THREAD

**Issue by viviel** [arana-db/arana#219]
**What happened**:

Client verison: 5.7.38

Command like: show tables; use databases; show databases; will report error

`ERROR 2013 (HY000): Lost connection to MySQL server during query`

**What you expected to happen**:

Should be executed correctly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by dongzl** [comment]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/5917359/173239926-704d80c5-b4c8-4027-89a1-b9e4eb3a6365.png">

**Comment by Penglq** [comment]
Caused by two reasons:
1、com_show_fields use db0, if table is shard table, tableName is table0 in db0
2、https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition
If COM_FIELD_LIST read default value cause error in payload.
![image](https://user-images.githubusercontent.com/14035922/173288157-2c3bc0a4-5244-4b98-bc5c-8d4825a21921.png)
